CREATE TABLE IF NOT EXISTS CUSTOMERS(
    C_ID TEXT PRIMARY KEY,
    NAME TEXT,
    ORDER_NO TEXT,
    PRODUCT TEXT,
    COUNTRY TEXT
);

INSERT INTO CUSTOMERS(C_ID,NAME,ORDER_NO,PRODUCT,COUNTRY) VALUES
('001','CINDY','20110','EARBUDS','INDIA'),
('002','MARK','20020','MICROPHONE','AUSTRALIA'),
('003','ANDREA','30010','SPEAKERS','AUSTRALIA'),
('004','GEORGIA','31000','CAMERA','UK'),
('005','JORJE','30020','PHONE CASE','CANADA'),
('006','ANDREW','20900','SCREEN PROTECTOR','USA'),
('007','COREN','30300','PHONE CHARM','USA');

SELECT * FROM CUSTOMERS 
WHERE NAME LIKE('A%');

SELECT * FROM CUSTOMERS
WHERE NAME LIKE('%OR%');

SELECT DISTINCT COUNTRY FROM CUSTOMERS;