CREATE TABLE IF NOT EXISTS EMPLOYEE(
    EMID TEXT PRIMARY KEY,
    NAME TEXT,
    COMPANY_NAME TEXT,
    SALARY REAL,
    DEPARTMENT TEXT,
    CATEGORY TEXT
);

INSERT INTO EMPLOYEE(EMID,NAME,COMPANY_NAME,SALARY,DEPARTMENT,CATEGORY) VALUES
('E01','MARK ZUCKER','FACEBOOK',289000,'MARKETING','FULL-TIME'),
('E02','ELOD MUSC','PAYPAL',387000,'ENGINEERING','FULL-TIME'),
('E03','MARTHA TIMER','FACEBOOK',8400,'IT','PART-TIME'),
('E04','TIM COOK','APPLE',4789300,'FINANCE','FULL-TIME'),
('E05','STEEP BOBS','APPLE',38900,'ENGINEERING','FULL-TIME'),
('E06','BILL BATE','MICROSOFT',48900,'IT','FULL-TIME'),
('E07','BLAKE SMITH','FACEBOOK',8600,'MARKETING','PART-TIME'),
('E08','GRAYSON HAWTHORNE','INTEL',378000,'FINANCE','FULL-TIME'),
('E09','EARL DARWINSON','PAYPAL',6700,'IT','PART-TIME'),
('E10','DREW SMITH','FACEBOOK',8900,'MARKETING','PART-TIME');

SELECT NAME,COMPANY_NAME,SALARY,CATEGORY FROM EMPLOYEE
WHERE CATEGORY='FULL-TIME'
ORDER BY SALARY DESC;

SELECT * FROM EMPLOYEE
WHERE CATEGORY='PART-TIME';

SELECT * FROM EMPLOYEE
WHERE CATEGORY='PART-TIME' AND DEPARTMENT='IT';

SELECT * FROM EMPLOYEE
WHERE COMPANY_NAME='FACEBOOK' AND CATEGORY='FULL-TIME';

SELECT * FROM EMPLOYEE
WHERE COMPANY_NAME='FACEBOOK' AND CATEGORY='PART-TIME';

